### ISSUE TITLE
SystemDisplayWrite does not actually write to the display

### ISSUE THREAD

**Issue by driverblock** [ms-iot/ScreenProvider#11]
VOID BASIC_DISPLAY_DRIVER::SystemDisplayWrite in BDD.cxx only copies to a frame buffer - does not write to SPI.

**Comment by saraclay** [comment]
Hi @driverblock, since this issue was opened a while ago, I will close it if any recent updates have fixed this. For future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs
